matrix:
  include:
    - language: python
      python: "3.6"
      before_install: cd python
      install: pip install tox-travis codecov
      script: tox
      after_success: codecov
    - language: python
      python: "3.7"
      before_install: cd python
      install: pip install tox-travis codecov
      script: tox
      after_success:
        codecov
    - name: "Linting and generic checks"
      language: python
      python: "3.7"
      install: pip install pre-commit
      script: pre-commit run --all-files --show-diff-on-failure
    - language: r
      r: release
      cache: packages
      warnings_are_errors: true
      before_install:
      - cd rpackage
      - echo $TRAVIS_BUILD_DIR
      - POSTERIOR_DB_PATH=$TRAVIS_BUILD_DIR
      - echo $POSTERIOR_DB_PATH
      - pwd
      r_packages: covr
      after_success: Rscript -e 'covr::codecov()'
