# Check posteriordb
name: check_posteriordb_content

on:
  push:
    branches:
      - master
      - development
  pull_request:
    branches:
      - master
      - development

jobs:
  models:
    name: Check posteriordb content
    runs-on: ${{ matrix.config.os }}
    strategy:
      matrix:
        config:
          - {os: ubuntu-latest,     r: 'release'}
      fail-fast: false
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@master

      - uses: r-lib/actions/setup-r@master

      - name: Install packages
        run: |
          R -e 'install.packages("remotes")'
          R -e 'remotes::install_github("stan-dev/posteriordb-r")'

      - name: Set PDB path
        run: export PDB_PATH=$GITHUB_WORKSPACE;echo $PDB_PATH;echo PDB_PATH="$PDB_PATH" >> ~/.Renviron;ls $PDB_PATH
        shell: bash

      - name: Check PDB content
        run: Rscript tests/hello_world.R
